### ISSUE TITLE
Make this role compatible with RedHat

### ISSUE THREAD

**Issue by palmerabollo** [griggheo/ansible-consul-template#10]
`apt` is not available in RedHat systems. What do you think about conditionally using `yum` (`when: ansible_os_family == "RedHat"`) in these systems?

**Comment by palmerabollo** [comment]
This works and make the role compatible with RH

```yaml
- name: install deps (RHEL)
  yum: >
    pkg={{ item }}
    state=installed
  with_items:
    - unzip
  when: ansible_os_family == "RedHat"
```
